#https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/recipes/docker-server/kubernetes/lhci-pod.yml
#https://hub.docker.com/r/patrickhulce/lhci-server

apiVersion: v1
kind: Pod
metadata:
  name: lhci-pod
  namespace: devops-lighthouse
  labels:
    name: lhci-pod
spec:
  containers:
    - name: lhci-server
      image: docker.io/patrickhulce/lhci-server:0.6.1
      volumeMounts:
        - mountPath: '/data'
          name: lhci-data-volume
  volumes:
    - name: lhci-data-volume
      persistentVolumeClaim:
        claimName: lhci-data-claim